version: '3.7'

services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    networks:
      - docker-service
    depends_on: 
      - mariadb
    
  mariadb:
    image: mariadb:latest
    container_name: docker-mariadb
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      - docker-service
    volumes:
      - maria-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management
    
    ports: 
    - 25672:25672 # (erlang) communication between the nodes and CLI tool
    - 15672:15672 # communication with the web management API 
    
    volumes:
    # data persistence
    - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
    # data mapping -> host: container
    # queues and messages data of the container will be stored on the host
    environment:
    - RABBITMQ_DEFAULT_USER = admin
    - RABBITMQ_DEFAULT_PASS = passw123

    restart: always

networks:
  docker-service:
    driver: bridge

volumes:
  maria-data:
    driver: local
  logs-folder:
    name: ${log_rabbitmq_management}
    driver: local